### ISSUE TITLE
env input is throwing a warning even though is documented as supported 

### ISSUE THREAD

**Issue by gugaiz** [bobheadxi/deployments#20] opened 2020-08-20 00:02 UTC
I set the `env:` input, but I got `##[warning]Unexpected input(s) 'env', valid inputs are ['token', 'step', 'auto_inactive', 'logs', 'desc', 'ref']`. On the readme there is an example with using that input.

The same happens for `status` and `development_id` throwing `##[warning]Unexpected input(s) 'status', 'deployment_id', valid inputs are ['token', 'step', 'auto_inactive', 'logs', 'desc', 'ref']`

**Comment by bobheadxi** [comment] 2020-08-20 14:18
this is a duplicate of https://github.com/bobheadxi/deployments/issues/14 :)

**Closed by bobheadxi** 2020-08-20 14:18 UTC
Labels: duplicate
