### ISSUE TITLE
Should my description input display in the deployments view?

### ISSUE THREAD

**Issue by johndesp** [bobheadxi/deployments#18] opened 2020-07-15 16:46 UTC
Hi. Based upon the documentation it seems you can provide a description using the "desc" input.

In the documentation here https://github.com/bobheadxi/deployments it looks like you have shown "This branch is being deployed".  My assumption is that This branch is being deployed" is a description.

Should the desc input below display in the deployments view during this deployment?

thanks

- name: GitHub Deployments
      uses: bobheadxi/deployments@master
      id: deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: dev
        desc: Starting a build and deploy JD

**Comment by bobheadxi** [comment] 2020-08-11 12:06
Hm - this parameter is provided to GitHub API calls correctly, how it gets displayed seems up to GitHub: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/bobheadxi/deployments%24+file:%5Esrc/main%5C.ts+description&patternType=literal

**Comment by vasek-b** [comment] 2020-10-05 22:12
Given the link to source code you provided - shouldn't it be added as `description: description` on lines 58 and 82 in main.ts?

**Comment by reeloadead** [comment] 2022-01-14 14:11
Hello, is this issue still relevant or fixed?

If fixed, could you please show how description displayed on UI as example
Because I still haven't see description text anywhere on pull request page in my project.
![image](https://user-images.githubusercontent.com/46749590/149528651-9facecee-a3ba-46ed-8b39-f51598bedb77.png)

**Comment by bobheadxi** [comment] 2022-02-21 23:36
Unfortunately I think this is a GitHub problem - even with a description set:

<img width="958" alt="image" src="https://user-images.githubusercontent.com/23356519/155038567-a920ad74-d2bf-478a-bd47-771a97c3cdb7.png">

The environment does not render the description:

<img width="782" alt="image" src="https://user-images.githubusercontent.com/23356519/155038585-6c3a5f49-e021-4129-a2cc-61fe0ce81536.png">

To resolve this we'll have to petition GitHub to render the description appropriately. I think this is a regression, I'm pretty sure this description used to render 🤔 oh well. Closing this for now!

**Closed by bobheadxi** 2022-02-21 23:36 UTC
Labels: bug
